"""
backend/core/security.py
-------------------------
Security helpers: input validation to prevent crashes and path traversal.

Why this module exists
----------------------
Two categories of real bugs caught before this file existed:

1. PATH TRAVERSAL — a filename like "../../../etc/passwd" could escape the
   storage folder when joined with Path():
       raw_dir / "../../../etc/passwd"
       = backend/storage/session/raw/../../../etc/passwd
       = backend/etc/passwd    ← WRONG directory!
   Fix: always use Path(filename).name to strip directory components.

2. SESSION ID INJECTION — a session_id like "../../etc" would let callers
   read arbitrary folders on disk. Since all our session_ids are UUID4s
   (generated by uuid.uuid4()), any non-UUID4 value is illegal.
   Fix: validate session_id matches UUID4 regex before using it in a Path.
"""

from __future__ import annotations

import math
import re
from pathlib import Path

from fastapi import HTTPException

# UUID4 format: xxxxxxxx-xxxx-4xxx-[89ab]xxx-xxxxxxxxxxxx
_UUID4_RE = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    re.IGNORECASE,
)


def validate_session_id(session_id: str) -> None:
    """
    Raise HTTP 400 if session_id is not a valid UUID4.

    This prevents:
    - Path traversal via session_id like "../../etc/passwd"
    - Arbitrary directory listing/reading
    - Confused-deputy attacks where an attacker reads another user's session
    """
    if not _UUID4_RE.match(session_id):
        raise HTTPException(
            status_code=400,
            detail=(
                f"Invalid session_id: '{session_id}'. "
                "Expected a UUID4 like 'a8098c1a-f86e-11da-bd1a-00112444be1e'."
            ),
        )


def safe_filename(filename: str | None) -> str:
    """
    Extract just the filename component (no directory parts).

    Prevents path traversal via uploaded filenames:
        "../../../etc/passwd"  →  "passwd"  (still rejected by extension check)
        "subdir/evil.mp3"      →  "evil.mp3"

    Also rejects empty filenames and names starting with '.'.

    Returns:
        The safe basename string.

    Raises:
        HTTP 400 if filename is empty or invalid.
    """
    if not filename:
        raise HTTPException(status_code=400, detail="Filename cannot be empty.")
    name = Path(filename).name  # strips all directory components
    if not name or name.startswith("."):
        raise HTTPException(
            status_code=400,
            detail=f"Invalid filename: '{filename}'.",
        )
    return name
